// HTML templates for the /alternatives/ comparison pages.
// Content lives in ./competitors/*.mjs; this file only renders it.
import { readFileSync } from "node:fs";

const SITE = "https://www.personalbestie.com";
const APP = "https://app.personalbestie.com";
const AUTHOR = { name: "Nicolas Leyton", url: `${APP}/about/` };

const styles = readFileSync(new URL("./styles.css", import.meta.url), "utf8");

export const esc = (value) =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");

const jsonLdScript = (graph) =>
  JSON.stringify({ "@context": "https://schema.org", "@graph": graph }, null, 4)
    .replaceAll("<", "\\u003c")
    .split("\n")
    .map((line) => `    ${line}`)
    .join("\n");

const cta = (campaign, classes, label) =>
  `<a href="${APP}?utm_source=alternatives&amp;utm_medium=cta&amp;utm_campaign=${campaign}" class="${classes}">${esc(label)}</a>`;

const cell = ({ kind = "plain", text }) => {
  const safe = esc(text);
  if (kind === "check") return `<td><span class="badge-check">✓ ${safe}</span></td>`;
  if (kind === "cross") return `<td><span class="badge-cross">✕ ${safe}</span></td>`;
  if (kind === "neutral") return `<td><span class="badge-neutral">${safe}</span></td>`;
  if (kind === "highlight") return `<td class="font-black text-[var(--primary-rose)]">${safe}</td>`;
  return `<td>${safe}</td>`;
};

const shell = ({ title, description, ogTitle, path, ogType = "website", graph, body, footerCurrent, alternatives }) => {
  const url = `${SITE}${path}`;
  const footerLinks = alternatives
    .map(({ slug, name }) => {
      const active = footerCurrent === slug;
      return `                    <a href="${SITE}/alternatives/${slug}/"
                        class="${active ? "text-[var(--primary-rose)] font-bold" : "hover:text-[var(--primary-rose)] transition-colors"}">${esc(name)} Alternative</a>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${esc(title)}</title>
    <meta name="description"
        content="${esc(description)}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="${ogType}">
    <meta property="og:url" content="${url}">
    <meta property="og:title" content="${esc(ogTitle)}">
    <meta property="og:description"
        content="${esc(description)}">
    <meta property="og:image" content="${SITE}/assets/icon-512.png">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:url" content="${url}">
    <meta name="twitter:title" content="${esc(ogTitle)}">
    <meta name="twitter:description"
        content="${esc(description)}">
    <meta name="twitter:image" content="${SITE}/assets/icon-512.png">

    <!-- Canonical & Icons -->
    <link rel="canonical" href="${url}">
    <link rel="icon" type="image/svg+xml" href="/favicon.svg">
    <link rel="icon" type="image/png" sizes="192x192" href="/assets/icon-192.png">
    <link rel="icon" type="image/png" sizes="512x512" href="/assets/icon-512.png">
    <link rel="shortcut icon" type="image/png" href="/assets/icon-192.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png">
    <meta name="theme-color" content="#f7f7f7">
    <link rel="alternate" type="text/plain" href="/llms.txt" title="LLMs.txt">

    <!-- Generated by scripts/build-alternatives.mjs from static-site/alternatives/. Do not edit by hand. -->
    <script type="application/ld+json">
${jsonLdScript(graph)}
    </script>

    <link rel="stylesheet" href="/static.css">
    <style>
        /* In the components layer so Tailwind utilities (static.css) can override these rules. */
        @layer components {
${styles}        }
    </style>
</head>

<body class="antialiased">
    <div class="relative mx-auto flex min-h-screen max-w-7xl flex-col px-4 sm:px-6 lg:px-8">
        <!-- Site Header -->
        <header class="py-6">
            <div class="glass-panel flex items-center justify-between px-6 py-4">
                <a href="${SITE}/" class="flex items-center gap-2 text-lg font-bold" aria-label="PersonalBestie Home">
                    <img alt="PersonalBestie Logo" class="h-8 w-8" src="/assets/logo.svg" width="32" height="32">
                    <div class="logo-wordmark flex flex-col items-start leading-none">
                        <span>Personal</span>
                        <span>Bestie</span>
                    </div>
                </a>
                <div class="flex items-center gap-6">
                    <a href="${SITE}/#features"
                        class="hidden text-sm font-bold uppercase tracking-wider opacity-60 hover:opacity-100 transition-opacity md:inline">Features</a>
                    <a href="${SITE}/blog/"
                        class="hidden text-sm font-bold uppercase tracking-wider opacity-60 hover:opacity-100 transition-opacity md:inline">Blog</a>
                    <a href="${APP}" class="btn btn-primary">Open App</a>
                </div>
            </div>
        </header>

${body}

        <!-- Site Footer -->
        <footer class="mt-12 border-t border-[var(--border)] py-12 text-sm text-[color:var(--muted-foreground)]">
            <div class="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
                <div>&copy; <span id="year"></span> PersonalBestie · Built by ${AUTHOR.name}</div>
                <div class="flex flex-wrap gap-6">
                    <a href="${APP}"
                        class="hover:text-[var(--primary-rose)] transition-colors">Open App</a>
                    <a href="${SITE}/"
                        class="hover:text-[var(--primary-rose)] transition-colors">Home</a>
${footerLinks}
                    <a href="${SITE}/blog/"
                        class="hover:text-[var(--primary-rose)] transition-colors">Blog</a>
                    <a href="/llms.txt" class="hover:text-[var(--primary-rose)] transition-colors">LLMs.txt</a>
                    <a href="mailto:ndleyton@uc.cl" class="hover:text-[var(--primary-rose)] transition-colors">Email</a>
                </div>
            </div>
        </footer>
    </div>

    <script>
        document.getElementById("year").textContent = new Date().getFullYear();
    </script>
</body>

</html>
`;
};

const breadcrumb = (current, { link = true } = {}) => `            <!-- Breadcrumbs -->
            <nav class="mb-6 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[color:var(--muted-foreground)]">
                <a href="${SITE}/" class="hover:text-[var(--primary-rose)] transition-colors">Home</a>
                <span>/</span>
                ${
                  link
                    ? `<a href="${SITE}/alternatives/" class="hover:text-[var(--primary-rose)] transition-colors">Alternatives</a>`
                    : `<span class="text-[var(--foreground)]">Alternatives</span>`
                }${
                  current
                    ? `
                <span>/</span>
                <span class="text-[var(--foreground)]">${esc(current)}</span>`
                    : ""
                }
            </nav>`;

const sourcesNote = ({ name, verified, sources }) => {
  const links = sources
    .map((source) =>
      source.url
        ? `<a href="${esc(source.url)}" rel="noopener" class="underline hover:text-[var(--primary-rose)]">${esc(source.label)}</a>`
        : esc(source.label),
    )
    .join(", ");
  return `            <!-- Sources -->
            <section class="my-8">
                <p class="text-xs leading-relaxed text-[color:var(--muted-foreground)]">
                    ${esc(name)} pricing and plan limits last verified on <time datetime="${verified}">${verified}</time> against: ${links}. Other feature details reflect publicly available information. Apps change often; if something here is out of date, <a href="mailto:ndleyton@uc.cl" class="underline hover:text-[var(--primary-rose)]">let us know</a>.
                </p>
            </section>`;
};

export const renderComparisonPage = (c, alternatives) => {
  const { name, slug } = c;
  const path = `/alternatives/${slug}/`;
  const url = `${SITE}${path}`;

  const graph = [
    {
      "@type": "Article",
      headline: c.seo.headline,
      description: c.seo.articleDescription,
      url,
      datePublished: c.published,
      dateModified: c.modified,
      author: { "@type": "Person", ...AUTHOR },
      publisher: { "@type": "Organization", name: "PersonalBestie", url: SITE },
    },
    {
      "@type": "FAQPage",
      mainEntity: c.faq.map(({ q, a }) => ({
        "@type": "Question",
        name: q,
        acceptedAnswer: { "@type": "Answer", text: a },
      })),
    },
  ];

  const verdictItems = c.verdict.items
    .map(
      ({ title, text }) => `                        <li class="flex items-start gap-2">
                            <span class="text-[var(--primary-rose)] font-bold text-lg leading-none">✓</span>
                            <span><strong>${esc(title)}</strong> ${esc(text)}</span>
                        </li>`,
    )
    .join("\n");

  const headers = c.table.columns
    .map((title) => `                                    <th class="font-bold">${esc(title)}</th>`)
    .join("\n");
  const rows = c.table.rows
    .map(
      ({ feature, cells }) => `                                <tr>
                                    <td class="font-semibold">${esc(feature)}</td>
${cells.map((item) => `                                    ${cell(item)}`).join("\n")}
                                </tr>`,
    )
    .join("\n");

  const reasons = c.reasons.items
    .map(
      ({ title, body }, index) => `                    <div class="glass-panel p-8">
                        <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--primary-rose-soft)] text-[var(--primary-rose)] font-black text-xl mb-4">
                            ${String(index + 1).padStart(2, "0")}
                        </div>
                        <h3 class="text-2xl font-bold">${esc(title)}</h3>
                        <p class="mt-3 leading-relaxed text-[color:var(--muted-foreground)]">
                            ${esc(body)}
                        </p>
                    </div>`,
    )
    .join("\n\n");

  const fair = c.fair.items
    .map(
      ({ title, body }) => `                        <div class="flex items-start gap-3">
                            <span class="text-base font-bold text-[var(--foreground)]">•</span>
                            <div>
                                <strong class="text-[var(--foreground)]">${esc(title)}</strong>
                                ${esc(body)}
                            </div>
                        </div>`,
    )
    .join("\n");

  const faq = c.faq
    .map(
      ({ q, a }) => `                    <details class="glass-panel p-6 group cursor-pointer">
                        <summary class="font-bold text-lg sm:text-xl flex items-center justify-between list-none">
                            <span>${esc(q)}</span>
                            <span class="text-[var(--primary-rose)] transition-transform group-open:rotate-180">↓</span>
                        </summary>
                        <p class="mt-4 leading-relaxed text-[color:var(--muted-foreground)]">
                            ${esc(a)}
                        </p>
                    </details>`,
    )
    .join("\n\n");

  const body = `        <main class="flex-1 py-8 sm:py-12">
${breadcrumb(`${name} Alternative`)}

            <!-- Hero Section -->
            <section class="max-w-4xl py-6 sm:py-10">
                <div class="caps-label inline-block">
                    ${esc(c.hero.eyebrow)}
                </div>
                <h1 class="text-glow mt-4 text-4xl font-black tracking-tight sm:text-6xl lg:text-7xl leading-[1.08]">
                    ${esc(c.hero.h1)}
                </h1>
                <p class="mt-6 text-xl leading-relaxed text-[color:var(--muted-foreground)] sm:text-2xl">
                    ${c.hero.leadHtml}
                </p>

                <div class="mt-10 flex flex-col gap-4 sm:flex-row">
                    ${cta(`${slug}_cta`, "btn btn-primary px-8 py-4 text-base", c.hero.primaryCta)}
                    ${cta(`${slug}_guest`, "btn btn-glass px-8 py-4 text-base", "Try as Guest · No Sign-Up")}
                </div>
                <p class="mt-3 text-xs text-[color:var(--muted-foreground)]">
                    Local-first in your browser. No credit card, no app store download required.
                </p>
            </section>

            <!-- Key Takeaways / TL;DR Box -->
            <section class="my-8">
                <div class="glass-panel p-6 sm:p-8 border-l-4 border-l-[var(--primary-rose)]">
                    <div class="caps-label">The Quick Verdict</div>
                    <h2 class="mt-2 text-2xl font-black tracking-tight">${esc(c.verdict.heading)}</h2>
                    <ul class="mt-4 grid gap-3 text-base text-[color:var(--muted-foreground)] sm:grid-cols-2">
${verdictItems}
                    </ul>
                </div>
            </section>

            <!-- Side-by-Side Comparison Table -->
            <section class="my-16">
                <div class="mb-8">
                    <div class="caps-label">Direct Comparison</div>
                    <h2 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">${esc(c.table.heading)}</h2>
                    <p class="mt-2 text-[color:var(--muted-foreground)]">${esc(c.table.intro)}</p>
                </div>

                <div class="glass-panel overflow-hidden">
                    <div class="overflow-x-auto">
                        <table class="w-full text-left comparison-table border-collapse text-sm sm:text-base">
                            <thead>
                                <tr class="bg-[rgba(var(--foreground-rgb),0.03)] text-[color:var(--muted-foreground)]">
                                    <th class="font-bold">Feature</th>
                                    <th class="font-extrabold text-[var(--primary-rose)]">PersonalBestie</th>
${headers}
                                </tr>
                            </thead>
                            <tbody>
${rows}
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>

            <!-- Detailed Reasons to Switch -->
            <section class="my-16 space-y-12">
                <div class="max-w-3xl">
                    <div class="caps-label">Deep Dive</div>
                    <h2 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">${esc(c.reasons.heading)}</h2>
                </div>

                <div class="grid gap-8 md:grid-cols-2">
${reasons}
                </div>
            </section>

            <!-- Honest Section: When the competitor is still right -->
            <section class="my-16">
                <div class="glass-panel p-8 sm:p-12">
                    <div class="caps-label">Fair & Balanced</div>
                    <h2 class="mt-2 text-2xl font-black tracking-tight sm:text-3xl">${esc(c.fair.heading)}</h2>
                    <p class="mt-4 leading-relaxed text-[color:var(--muted-foreground)]">
                        ${esc(c.fair.intro)}
                    </p>
                    <div class="mt-6 space-y-4 text-[color:var(--muted-foreground)]">
${fair}
                    </div>
                </div>
            </section>

            <!-- FAQ Section -->
            <section class="my-16">
                <div class="mb-8">
                    <div class="caps-label">Common Questions</div>
                    <h2 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Frequently asked questions</h2>
                </div>

                <div class="space-y-4">
${faq}
                </div>
            </section>

${sourcesNote(c)}

            <!-- Bottom CTA Banner -->
            <section class="my-16">
                <div class="glass-panel p-8 sm:p-14 text-center flex flex-col items-center">
                    <div class="caps-label">${esc(c.cta.label)}</div>
                    <h2 class="mt-3 text-3xl font-black tracking-tight sm:text-5xl max-w-2xl leading-tight">
                        ${esc(c.cta.heading)}
                    </h2>
                    <p class="mt-4 text-lg text-[color:var(--muted-foreground)] max-w-xl">
                        ${esc(c.cta.body)}
                    </p>
                    <div class="mt-8 flex flex-col sm:flex-row gap-4">
                        ${cta(`${slug}_bottom_cta`, "btn btn-primary px-8 py-4 text-base", "Open PersonalBestie Free")}
                        <a href="${SITE}/alternatives/" class="btn btn-glass px-8 py-4 text-base">
                            More Comparisons
                        </a>
                    </div>
                </div>
            </section>
        </main>`;

  return shell({
    title: c.seo.title,
    description: c.seo.description,
    ogTitle: c.seo.ogTitle,
    path,
    graph,
    body,
    footerCurrent: slug,
    alternatives,
  });
};

export const renderIndexPage = (alternatives) => {
  const description =
    "Compare PersonalBestie with other workout apps on features, pricing, and training workflows.";
  const graph = [
    {
      "@type": "CollectionPage",
      name: "Workout tracker comparisons",
      description,
      url: `${SITE}/alternatives/`,
      hasPart: alternatives.map(({ slug, seo }) => ({
        "@type": "Article",
        headline: seo.headline,
        url: `${SITE}/alternatives/${slug}/`,
      })),
    },
  ];

  const cards = alternatives
    .map(
      ({ slug, name, indexBlurb }) => `                    <a href="${SITE}/alternatives/${slug}/" class="glass-panel block p-8">
                        <div class="caps-label">PersonalBestie vs ${esc(name)}</div>
                        <h2 class="mt-2 text-2xl font-black tracking-tight">${esc(name)} alternative</h2>
                        <p class="mt-3 leading-relaxed text-[color:var(--muted-foreground)]">${esc(indexBlurb)}</p>
                        <span class="mt-4 inline-block text-sm font-bold uppercase tracking-wider text-[var(--primary-rose)]">Read the comparison →</span>
                    </a>`,
    )
    .join("\n");

  const body = `        <main class="flex-1 py-8 sm:py-12">
${breadcrumb(null, { link: false })}

            <section class="max-w-4xl py-6 sm:py-10">
                <div class="caps-label inline-block">Comparisons · ${esc(alternatives.map((c) => c.modified).sort().at(-1)?.slice(0, 4) ?? "")}</div>
                <h1 class="text-glow mt-4 text-4xl font-black tracking-tight sm:text-6xl leading-[1.08]">
                    PersonalBestie vs other workout apps
                </h1>
                <p class="mt-6 text-xl leading-relaxed text-[color:var(--muted-foreground)]">
                    Honest side-by-side comparisons, including where each app is still the better pick.
                </p>
            </section>

            <section class="my-8">
                <div class="grid gap-8 md:grid-cols-2">
${cards}
                </div>
            </section>
        </main>`;

  return shell({
    title: "Workout App Comparisons | PersonalBestie",
    description,
    ogTitle: "Workout App Comparisons | PersonalBestie",
    path: "/alternatives/",
    graph,
    body,
    footerCurrent: null,
    alternatives,
  });
};

export const renderSitemapBlock = (alternatives) =>
  [
    { path: "/alternatives/", lastmod: alternatives.map((c) => c.modified).sort().at(-1), priority: "0.8" },
    ...alternatives.map((c) => ({ path: `/alternatives/${c.slug}/`, lastmod: c.modified, priority: "0.9" })),
  ]
    .map(
      ({ path, lastmod, priority }) => `  <url>
    <loc>${SITE}${path}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${priority}</priority>
  </url>`,
    )
    .join("\n");

export const renderLlmsBlock = (alternatives) =>
  [
    "- `/alternatives/`: index of PersonalBestie comparisons with other workout apps",
    ...alternatives.map((c) => `- \`/alternatives/${c.slug}/\`: ${c.llmsSummary}`),
  ].join("\n");
