import type { GuestRecipe } from "../useGuestStore";
import type { ExerciseTypeIds } from "./types";

export const buildRecipes = (
  ids: ExerciseTypeIds,
  generateId: () => string,
): GuestRecipe[] =>
  [
    {
      id: generateId(),
      name: "Pull Routine",
      description:
        "Comprehensive back and bicep workout for muscle building and strength",
      visibility: "public",
      is_readonly: true,
      exercises: [
        {
          id: generateId(),
          exercise_type_id: ids.pullUps,
          exercise_type: {
            id: ids.pullUps,
            name: "Pull-ups",
            description: "Upper body bodyweight pulling exercise",
            default_intensity_unit: 5,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 8,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 6,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 90,
            },
          ],
          notes: "Focus on controlled movement and full range of motion",
        },
        {
          id: generateId(),
          exercise_type_id: ids.barbellRows,
          exercise_type: {
            id: ids.barbellRows,
            name: "Barbell Row",
            description: "Back strength exercise",
            default_intensity_unit: 1,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 8,
              intensity: 135,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 135,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 135,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
          ],
          notes: "Keep core tight, pull to lower chest",
        },
        {
          id: generateId(),
          exercise_type_id: ids.latPulldowns,
          exercise_type: {
            id: ids.latPulldowns,
            name: "Lat Pulldowns",
            description: "Upper back and lat exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 12,
              intensity: 120,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 130,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 140,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
          ],
          notes: "Pull to upper chest, squeeze lats",
        },
        {
          id: generateId(),
          exercise_type_id: ids.facePulls,
          exercise_type: {
            id: ids.facePulls,
            name: "Face Pulls",
            description: "Rear deltoid and upper back exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 15,
              intensity: 50,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 15,
              intensity: 60,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 12,
              intensity: 70,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
          ],
          notes: "Pull to face level, external rotation",
        },
        {
          id: generateId(),
          exercise_type_id: ids.bicepCurls,
          exercise_type: {
            id: ids.bicepCurls,
            name: "Bicep Curls",
            description: "Bicep isolation exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 12,
              intensity: 25,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 30,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 35,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
          ],
          notes: "Strict form, no swinging",
        },
        {
          id: generateId(),
          exercise_type_id: ids.hammerCurls,
          exercise_type: {
            id: ids.hammerCurls,
            name: "Hammer Curls",
            description: "Bicep and forearm exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 12,
              intensity: 25,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 12,
              intensity: 25,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
          ],
          notes: "Neutral grip, control the negative",
        },
      ],
      created_at: "2025-01-01T00:00:00.000Z",
      updated_at: "2025-01-01T00:00:00.000Z",
    },
    {
      id: generateId(),
      name: "Push Routine",
      description:
        "Complete chest, shoulders, and tricep workout for upper body power",
      visibility: "public",
      is_readonly: true,
      exercises: [
        {
          id: generateId(),
          exercise_type_id: ids.benchPress,
          exercise_type: {
            id: ids.benchPress,
            name: "Bench Press",
            description: "Upper body strength exercise",
            default_intensity_unit: 1,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 8,
              intensity: 185,
              intensity_unit_id: 2,
              rest_time_seconds: 180,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 185,
              intensity_unit_id: 2,
              rest_time_seconds: 180,
            },
            {
              id: generateId(),
              reps: 6,
              intensity: 205,
              intensity_unit_id: 2,
              rest_time_seconds: 180,
            },
          ],
          notes: "Control the bar, pause at chest",
        },
        {
          id: generateId(),
          exercise_type_id: ids.inclineBenchPress,
          exercise_type: {
            id: ids.inclineBenchPress,
            name: "Incline Bench Press",
            description: "Upper chest strength exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 10,
              intensity: 135,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 155,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 6,
              intensity: 165,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
          ],
          notes: "30-45 degree incline, focus on upper chest",
        },
        {
          id: generateId(),
          exercise_type_id: ids.overheadPress,
          exercise_type: {
            id: ids.overheadPress,
            name: "Overhead Press",
            description: "Shoulder and tricep exercise",
            default_intensity_unit: 1,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 8,
              intensity: 95,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 95,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 6,
              intensity: 105,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
          ],
          notes: "Standing press, core engaged",
        },
        {
          id: generateId(),
          exercise_type_id: ids.dips,
          exercise_type: {
            id: ids.dips,
            name: "Dips",
            description: "Tricep and chest bodyweight exercise",
            default_intensity_unit: 5,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 10,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 6,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 90,
            },
          ],
          notes: "Full range of motion, lean forward slightly",
        },
        {
          id: generateId(),
          exercise_type_id: ids.lateralRaises,
          exercise_type: {
            id: ids.lateralRaises,
            name: "Lateral Raises",
            description: "Side deltoid exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 15,
              intensity: 15,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 12,
              intensity: 20,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 25,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
          ],
          notes: "Controlled movement, slight forward lean",
        },
        {
          id: generateId(),
          exercise_type_id: ids.tricepExtensions,
          exercise_type: {
            id: ids.tricepExtensions,
            name: "Tricep Extensions",
            description: "Tricep isolation exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 12,
              intensity: 60,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 70,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 80,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
          ],
          notes: "Keep elbows stationary, full extension",
        },
      ],
      created_at: "2025-01-01T00:00:00.000Z",
      updated_at: "2025-01-01T00:00:00.000Z",
    },
    {
      id: generateId(),
      name: "Legs Routine",
      description:
        "Complete lower body workout targeting quads, hamstrings, glutes, and calves",
      visibility: "public",
      is_readonly: true,
      exercises: [
        {
          id: generateId(),
          exercise_type_id: ids.squats,
          exercise_type: {
            id: ids.squats,
            name: "Squat",
            description: "Lower body bodyweight exercise",
            default_intensity_unit: 1,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 10,
              intensity: 185,
              intensity_unit_id: 2,
              rest_time_seconds: 180,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 205,
              intensity_unit_id: 2,
              rest_time_seconds: 180,
            },
            {
              id: generateId(),
              reps: 6,
              intensity: 225,
              intensity_unit_id: 2,
              rest_time_seconds: 180,
            },
          ],
          notes: "Below parallel, drive through heels",
        },
        {
          id: generateId(),
          exercise_type_id: ids.romanianDeadlifts,
          exercise_type: {
            id: ids.romanianDeadlifts,
            name: "Romanian Deadlifts",
            description: "Hamstring and glute exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 10,
              intensity: 135,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 155,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
            {
              id: generateId(),
              reps: 8,
              intensity: 155,
              intensity_unit_id: 2,
              rest_time_seconds: 120,
            },
          ],
          notes: "Hip hinge movement, feel hamstring stretch",
        },
        {
          id: generateId(),
          exercise_type_id: ids.bulgarianSplitSquats,
          exercise_type: {
            id: ids.bulgarianSplitSquats,
            name: "Bulgarian Split Squats",
            description: "Single leg quad and glute exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 12,
              intensity: 25,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 35,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 35,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
          ],
          notes: "Each leg, maintain balance and control",
        },
        {
          id: generateId(),
          exercise_type_id: ids.legPress,
          exercise_type: {
            id: ids.legPress,
            name: "Leg Press",
            description: "Quad and glute machine exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 15,
              intensity: 270,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 12,
              intensity: 315,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 360,
              intensity_unit_id: 2,
              rest_time_seconds: 90,
            },
          ],
          notes: "Full range of motion, controlled movement",
        },
        {
          id: generateId(),
          exercise_type_id: ids.walkingLunges,
          exercise_type: {
            id: ids.walkingLunges,
            name: "Walking Lunges",
            description: "Dynamic leg and glute exercise",
            default_intensity_unit: 1,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 20,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 20,
              intensity: null,
              intensity_unit_id: 1,
              rest_time_seconds: 60,
            },
          ],
          notes: "10 per leg, step out far, knee to 90 degrees",
        },
        {
          id: generateId(),
          exercise_type_id: ids.legCurls,
          exercise_type: {
            id: ids.legCurls,
            name: "Leg Curls",
            description: "Hamstring isolation exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 15,
              intensity: 80,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 12,
              intensity: 90,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
            {
              id: generateId(),
              reps: 10,
              intensity: 100,
              intensity_unit_id: 2,
              rest_time_seconds: 60,
            },
          ],
          notes: "Slow negative, squeeze at top",
        },
        {
          id: generateId(),
          exercise_type_id: ids.calfRaises,
          exercise_type: {
            id: ids.calfRaises,
            name: "Calf Raises",
            description: "Calf muscle exercise",
            default_intensity_unit: 2,
            times_used: 0,
          },
          sets: [
            {
              id: generateId(),
              reps: 20,
              intensity: 100,
              intensity_unit_id: 2,
              rest_time_seconds: 45,
            },
            {
              id: generateId(),
              reps: 15,
              intensity: 120,
              intensity_unit_id: 2,
              rest_time_seconds: 45,
            },
            {
              id: generateId(),
              reps: 12,
              intensity: 140,
              intensity_unit_id: 2,
              rest_time_seconds: 45,
            },
          ],
          notes: "Full range of motion, pause at top",
        },
      ],
      created_at: "2025-01-01T00:00:00.000Z",
      updated_at: "2025-01-01T00:00:00.000Z",
    },
  ] satisfies GuestRecipe[];
