"""change external_id to string

Revision ID: 148a1c691036
Revises: 924abd7d23b5
Create Date: 2025-07-12 12:28:58.453429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "148a1c691036"
down_revision: Union[str, None] = "924abd7d23b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED: op.drop_table('set_templates') - DO NOT DROP TABLES
    # REMOVED: op.drop_table('exercise_templates') - DO NOT DROP TABLES
    # REMOVED: op.drop_table('recipes') - DO NOT DROP TABLES
    op.alter_column(
        "exercise_types",
        "external_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exercise_types",
        "external_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # NOTE: Table recreation removed - those tables should remain as-is
    # ### end Alembic commands ###
