"""add_deleted_at_to_exercise_sets

Revision ID: 8fe769cc294e
Revises: e99108c5936e
Create Date: 2025-08-06 19:17:24.800058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fe769cc294e"
down_revision: Union[str, None] = "e99108c5936e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercise_sets",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exercise_sets", "deleted_at")
    # ### end Alembic commands ###
