"""add external_id and images_url to exercise_types

Revision ID: 924abd7d23b5
Revises: d0ed48d5a1b9
Create Date: 2025-07-10 12:25:38.635607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "924abd7d23b5"
down_revision: Union[str, None] = "d0ed48d5a1b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exercise_types", sa.Column("external_id", sa.Integer(), nullable=True)
    )
    op.add_column("exercise_types", sa.Column("images_url", sa.Text(), nullable=True))
    op.create_unique_constraint(None, "exercise_types", ["external_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "exercise_types", type_="unique")
    op.drop_column("exercise_types", "images_url")
    op.drop_column("exercise_types", "external_id")
    # ### end Alembic commands ###
