"""add recap column to workouts

Revision ID: b60b7cbbd60b
Revises: b2be93819887
Create Date: 2026-04-01 02:51:31.816399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60b7cbbd60b'
down_revision: Union[str, None] = 'b2be93819887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exercises_deleted_at', table_name='exercises')
    op.drop_column('users', 'timezone')
    op.add_column('workouts', sa.Column('recap', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'recap')
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=64), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False))
    op.create_index('idx_exercises_deleted_at', 'exercises', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
