"""Change intensity column to Numeric(7,3)

Revision ID: cb93f7d5492e
Revises: 8fe769cc294e
Create Date: 2025-08-29 18:39:38.657423

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cb93f7d5492e'
down_revision: Union[str, None] = '8fe769cc294e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE exercise_sets ALTER COLUMN intensity TYPE NUMERIC(7,3) USING intensity::NUMERIC(7,3)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE exercise_sets ALTER COLUMN intensity TYPE DOUBLE PRECISION USING intensity::DOUBLE PRECISION")
    # ### end Alembic commands ###
